### ISSUE TITLE
Remove 3rd-party dependencies in favour of native solution

### ISSUE THREAD

**Issue by snowtema** [Teknasyon-Teknoloji/desk360-ios-sdk#27]
### Proposition
1. Change SnapKit dependency in favour of `NSLayoutConstraint`
2. Change Moya to `URLSession`

### Motivation
I'm trying to do not to use the 3rd-party library in my projects where it is possible for a few reasons:
- I don't want to depend on another codebase;
- in most cases I use 5-10% of available features;
- I want to control the whole process and each part of my project as possible;
- I don't want to increase the build time of my project and binary size;
- I want to fix problems asap and not wait while contributors approve my PR to 3rd-party libs;

So, I think using 3rd-party libraries(e.g. SnapKit) in other 3rd-parties libraries (Desk360) should be if you can not do things in another way by yourself. 

PS. I understand why were you using SnapKit and Moya, you were probably trying to save time and develop faster, but you develop not a private project only for yourself, and it means you have to think not only for yourself but about possible problems for your clients.
PPS. You have up to 10 views where you were using SnapKit and 7 requests to API.

**Comment by osmanyildirim** [comment]
Hi @snowtema ,

Thanks for the feedback we will do it in our plans.
